// Generated by https://quicktype.io

export interface Donutlist {
    count:   number;
    results: Result[];
}

export interface Result {
    id:                number;
    ref:               string;
    name:              string;
    photo:             string;
    photo_attribution: string;
}
export interface Donutdetails {
}
